

controller_manager:
  ros__parameters:
    update_rate: 100 

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names: ["driver_wheel_left_joint"]
      right_wheel_names: ["driver_wheel_right_joint"]
      wheel_separation: 0.95
      wheel_radius: 0.16225      
      cmd_vel_timeout: 0.25       # seconds
      publish_rate: 50            # Hz
      velocity_rolling_window_size: 2
      enable_odom_tf: true
      base_frame_id: "base_link"
      odom_frame_id: "odom"
      command_interfaces: ["velocity"]
      state_interfaces: ["position", "velocity"]
