controller_manager:
  ros__parameters:
    update_rate: 100

    arm_controller: 
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters: 
    joints:
      - manipulator_base_shoulder_joint
      - manipulator_shoulder_link_joint
      - manipulator_link_elbow_joint
      - manipulator_elbow_wrist_joint
      - manipulator_wrist_gripper_joint 

    command_interfaces:
      - position
    state_interfaces:
      - position
    open_loop_control: true
    allow_integration_in_goal_trajectories: true

   


