controller_manager:
  ros__parameters:
    update_rate: 100

    arm_controller: 
      type: position_controllers/JointGroupPositionController

    wheel_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters: 
    joints:
      - manipulator_base_shoulder_joint
      - manipulator_shoulder_link_joint
      - manipulator_link_elbow_joint
      - manipulator_elbow_wrist_joint
      - manipulator_wrist_gripper_joint 

    command_interfaces:
      - position
    state_interfaces:
      - position
    open_loop_control: true

wheel_controller:
  ros__parameters: 

    use_stamped_vel: false

    left_wheel_names: ['driver_wheel_left_joint']

    right_wheel_names: ['driver_wheel_right_joint']

    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
      
    open_loop_control: true

    odom_frame_id: odom
    base_frame_id: mobile_robot_body

    publish_rate: 100.0
    cmd_vel_timeout: 0.5

    wheel_separation: 0.95
    wheel_radius: 0.16225


